### ISSUE TITLE
Some CSS improvement needed

### ISSUE THREAD

**Issue by GN13008** [GN13008/sailsessions#124]
- Search bar in search sessions section
- map size in the show
- add a comment in profil show
- back button in profil show

**Comment by Phlaurands** [comment]
some questions, add comment le bouton tu veux l'enlever c'est ca ? limite enlever tout les comment aussi tant que c'est pas une vrai fonctionnalité
et back btn tu veux faire quoi ?

**Comment by GN13008** [comment]
le boutons commentaire il est immense sur PC classique le mettre à la même taille que les commentaires peut être inclure dans la div quoi

le boutons back il est dans le coin a gauche alors que sur les autres pages il reste dans la div "iphone"
